//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTabanlıProgramlamaOdev2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int OgrID { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public string OgrBolum { get; set; }
        public string OgrMail { get; set; }
        public Nullable<int> OgrYas { get; set; }
    }
}
